name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day, automatically
  workflow_dispatch:        # lets you also run it manually anytime
  push:
    branches:
      - main               # regenerates whenever you push to main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake image
        uses: Platane/snk@v3
        with:
          github_user_name: sankar-prog
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake image to a special branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
